# Generated by Django 5.2.5 on 2025-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
