# Generated by Django 5.2.5 on 2025-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_notice_created_by_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='conflicts',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='base.work'),
        ),
    ]
