# Generated by Django 5.2.6 on 2025-09-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_feedback_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='conflicts',
            field=models.ManyToManyField(blank=True, to='base.work'),
        ),
    ]
